#!/usr/bin/env python3

import json
import subprocess

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk  # noqa: E402


# TODO(PM): Handle multiple workspaces in focus
def get_focused_workspace_num():
    """Return the number of the first workspace that is in focus"""
    workspaces = subprocess.check_output(['i3-msg', '-t', 'get_workspaces'])
    workspaces = json.loads(workspaces)
    for workspace in workspaces:
        if workspace['focused']:
            return (workspace['num'], workspace['name'])

    raise RuntimeError("No workspaces are in focus")


def update_focused_workspace_name(entry):
    num, old_name = get_focused_workspace_num()
    cmd = f'rename workspace "{old_name}" to "{num}: {entry.get_text()}"'
    subprocess.check_output(['i3-msg', cmd])
    # TODO(PM): Correct way to exit here?
    Gtk.main_quit()


def main():
    window = Gtk.Window(Gtk.WindowType.TOPLEVEL)
    window.set_title('Rename workspace')
    window.set_modal(True)
    window.set_position(Gtk.WindowPosition.CENTER_ON_PARENT)
    window.connect('destroy', Gtk.main_quit)

    entry = Gtk.Entry()
    entry.connect('activate', update_focused_workspace_name)
    # TODO(PM): Exit on escape key
    window.add(entry)

    window.show_all()

    Gtk.main()


if __name__ == '__main__':
    main()
